apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Cert-Manager
- ../common/cert-manager/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
# Istio
- ../common/istio-1-16/istio-crds/base
- ../common/istio-1-16/istio-namespace/base
- ../common/istio-1-16/istio-install/base
# OIDC Authservice
# - ../common/oidc-authservice/base
# Dex
# - ../common/dex/overlays/istio
# KNative (build, deploy, and manage modern serverless workloads, not used)
# - ../common/knative/knative-serving/overlays/gateways
# - ../common/knative/knative-eventing/base
- ../common/istio-1-16/cluster-local-gateway/base
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-16/kubeflow-istio-resources/base


# Kubeflow Pipelines
# - ../apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
# Katib
# - ../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook (used for poddefaults)
- ../apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App (notebook submission frontend)
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller (notebook submission backend)
- ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM (handling profiles)
- ../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller (tool for providing the measurements and visualizations needed during the machine learning workflow, not used)
# -  ../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App (tool for providing the measurements and visualizations needed during the machine learning workflow, not used)
# -  ../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator (used for scalable distributed training of machine learning (ML) models, not used)
# - ../apps/training-operator/upstream/overlays/kubeflow
# User namespace (creates the kubeflow-user-example-com profile, not required)
- ../common/user-namespace/base

# KServe (Model Inference Platform for k8s, not used)
# - ../contrib/kserve/kserve
# - ../contrib/kserve/models-web-app/overlays/kubeflow
