name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker:26-dind

    steps:
    - uses: actions/checkout@v2

    - name: "Install dependencies"
      run: |
        apk add make

    - run: ls -alh
